const io = require("../io")

io.write("Escreva até 20 números:")
const numero1 = io.readInt()
const numero2 = io.readInt()
const numero3 = io.readInt()
const numero4 = io.readInt()
const numero5 = io.readInt()
const numero6 = io.readInt()
const numero7 = io.readInt()
const numero8 = io.readInt()
const numero9 = io.readInt()
const numero10 = io.readInt()
const numero11 = io.readInt()
const numero12 = io.readInt()
const numero13 = io.readInt()
const numero14 = io.readInt()
const numero15 = io.readInt()
const numero16 = io.readInt()
const numero17 = io.readInt()
const numero18 = io.readInt()
const numero19 = io.readInt()
const numero20 = io.readInt()

io.write("A média aritimética é: " + (numero1 + numero2 + numero3 + numero4 + numero5 + numero6 + numero7 + numero8 + numero9 + numero10 + numero11 + numero12 + numero13 + numero14 + numero15 + numero16 + numero17 + numero18 + numero19 + numero20) / 20)